### ISSUE TITLE
Status of master

### ISSUE THREAD

**Issue by rookie10** [emphasize/DoorPi#1]
Pjsua hab ich zwischenzeitlich am laufen. Grundsätzlich sieht es auch eine Videoübertragung vor. Ob und wie jezt der PiKamera stream in die Sip übertragung eingebunden werden kann hab/kann ich derzeitig nicht testen können , mangels Hardware. Da die FB sowieso keine Bildübertragung unterstütz muss zusätzlich noch ein Sip Server eingerichtet werden mit dem man dann einen möglichen Stream testen kann. Piface geht auch lässt sich aber noch nicht ordnugsgemäß beenden, da stehe ich gerade auf dem schlauch
Anrufen von Pjsua führt derzeitig noch zum Absturz.

@emphasize @leoguiders @Pampersjoe wenn ich es richtig verstanden habe wollen wir die Diskussion hier weiter führen

**Comment by leoguiders** [comment]
Läuft auf der FB nicht sowieso ein SIP Server, und muss der Video nicht nur vermitteln?
Ansonsten ist FreePBX im Docker Container relativ simpel zu installieren zum testen.

**Comment by emphasize** [comment]
jo, hier ist besser, da wuestengecko die Entwicklung abrupt abebrochen hat.

**Comment by Pampersjoe** [comment]
Können wir machen und ja... FB ist sozusagen ein SIP-Server woran sich ja die Clients anmelden. Richtest in der Fritzbox DoorPi nicht als SIP-Client sondern als Türklingel ein, so kannst da auch eine URL zu einer IP-Kamera oder halt dem Pi hinterlegen mit dem MJPG-Stream oder wie das damals hieß, falls das irgendwie hilft?

**Comment by emphasize** [comment]
Natürlich ist FB _eine_ Möglichkeit des routings, allerdings ncht die alleinige (nur um das im Hinterkopf zu behalten - und nicht darauf hin zu konzipieren)

**Comment by Pampersjoe** [comment]
Find ich gut =) nicht jeder hat eine Fritzbox =)

**Comment by emphasize** [comment]
Ich werde das Wochenende eine Zusammenstellung der Änderungen (bzgl. webconfig) machen und die bebildert als issue reinstellen, die man auch als wiki-part weiterverarbeiten kann. 
Sind heute wieder Änderungen dazugekommen, wie zb die Verarbeitung von Listeneinträgen.

**Comment by motom001** [comment]
Wollen wir morgen ggf. ab 21 Uhr im Discord von Pampersjoe reden?
https://discord.com/channels/934063425263374387/934074828711936000

**Comment by rookie10** [comment]
Ich bin mir nicht sicher ob ich euch wirklich unterstützen kann. Meine Programmierkunst ist 5 Ligen drunter. Samstag prime time gibt auch noch ärger mit dem Chef. 
Ich möchte mich aber nicht drücken, sollte sich was ergeben schau ich das ich dazu komm

**Comment by emphasize** [comment]
discord erzählt mir das ich an "einem seltsamen Ort" bin 😛

**Comment by Pampersjoe** [comment]
https://discord.gg/mGba3G47S2

das sollte besser gehen =)

**Comment by emphasize** [comment]
Wollte nochmal eingehen auf die Frage __"Was passiert bei Fehleingaben"__ in der __webconfig__, denn nicht in jedem Fall wird der startup davon beeinträchtigt. Darüber hinaus bezieht sich das nur auf _registrierungsrelevante_ Bestandteile.

Gebe ich eine undefinierte(s) Event/Aktion ein wird das doorpi natürlich nicht initialisieren können
Eingaben wie diese werden natürlich momentan den statup abbrechen

<img src="https://user-images.githubusercontent.com/25036977/153751907-b95687c3-f982-4754-97f6-0066de56b9a4.jpg" width="500">

__Lösung:__ kontextbezogene form inputs. In dem Fall statt des `Keyname` eine drop down liste der registrierten Events (API call, da diese nicht Teil des vorhandenen [oConfigObject](https://github.com/emphasize/DoorPi/blob/4d02b23fe8f0fa28d6ff9462d7e9c3faff2a5a89/doorpi/web/templates/dashboard/pages/config.html#L59) sind; status.modules.event_handler.html macht einen solchen [hier](https://github.com/emphasize/DoorPi/blob/4d02b23fe8f0fa28d6ff9462d7e9c3faff2a5a89/doorpi/web/templates/dashboard/pages/status.modules.eventhandler.html#L167) bzw. [hier](https://github.com/emphasize/DoorPi/blob/4d02b23fe8f0fa28d6ff9462d7e9c3faff2a5a89/doorpi/web/templates/dashboard/pages/status.modules.eventhandler.html#L196))

Durch Type casting/value checking ist es aber bei manchen Eingaben gar nicht möglich diese zu speichern

_Beispiel:_ ip port
_Definition:_ [source](https://github.com/emphasize/DoorPi/blob/79cede695945d72ae2176c9d864c703a21444701/doorpi/config/defs/web.toml#L25)

<img src="https://user-images.githubusercontent.com/25036977/153752259-2cffee2a-1e75-47dd-97e7-49e023a7ed40.jpg" width="200">

die Eingabe eines werts außerhalb der Schranken (ie: type=int; in range(...)) führt zu einer Anzeige, das dies nicht möglich ist

<img src="https://user-images.githubusercontent.com/25036977/153752329-7640514d-2897-4155-858f-05d64aa86ce1.jpg" width="300">

Das gleiche gilt für Wahrheitswerte, Pfade, Floats. Definiert [hier](https://github.com/emphasize/DoorPi/blob/master/doorpi/config/types.py)

**Comment by rookie10** [comment]
irgendwie hoppelt die installation noch 

    Installed /usr/local/lib/python3.9/dist-packages/pyasn1_modules-0.2.8-py3.9.egg 
    Searching for pyasn1
    Downloading https://files.pythonhosted.org/packages/88/87/72eb9ccf8a58021c542de2588a867dbefc7556e14b2866d1e40e9e2b587e/pyasn1-modules-0.2.8.tar.gz#sha256=905f84c712230b2c592c19470d3ca8d552de726050d1d1716282a1f6146be65e
    Best match: pyasn1 modules-0.2.8
    Processing pyasn1-modules-0.2.8.tar.gz
    Writing /tmp/easy_install-sowzv99d/pyasn1-modules-0.2.8/setup.cfg
    Running pyasn1-modules-0.2.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-sowzv99d/pyasn1-modules-0.2.8/egg-dist-tmp-skssegpa
    listing git files failed - pretending there aren't any
    no previously-included directories found matching 'doc/build'
    removing '/usr/local/lib/python3.9/dist-packages/pyasn1_modules-0.2.8-py3.9.egg' (and everything under it) 
    Moving pyasn1_modules-0.2.8-py3.9.egg to /usr/local/lib/python3.9/dist-packages
    pyasn1-modules 0.2.8 is already the active version in easy-install.pth

    Installed /usr/local/lib/python3.9/dist-packages/pyasn1_modules-0.2.8-py3.9.egg
    error: The 'pyasn1' distribution was not found and is required by service-identity
    root@raspberrypi:/tmp/DoorPi#

bei Wiederholung kommt dann ein

```
Installed /usr/local/lib/python3.9/dist-packages/pyasn1-0.4.8-py3.9.egg
Searching for cryptography
Reading https://pypi.org/simple/cryptography/
Downloading https://files.pythonhosted.org/packages/f9/4b/1cf8e281f7ae4046a59e5e39dd7471d46db9f61bb564fddbff9084c4334f/cryptography-36.0.1.tar.gz#sha256=53e5c1dc3d7a953de055d77bef2ff607ceef7a2aac0353b5d630ab67f7423638
Best match: cryptography 36.0.1
Processing cryptography-36.0.1.tar.gz
Writing /tmp/easy_install-yjiuk3or/cryptography-36.0.1/setup.cfg
Running cryptography-36.0.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-yjiuk3or/cryptography-36.0.1/egg-dist-tmp-3n__wfn1

        =============================DEBUG ASSISTANCE==========================
        If you are seeing an error here please try the following to
        successfully install cryptography:

        Upgrade to the latest pip and try again. This will fix errors for most
        users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
        =============================DEBUG ASSISTANCE==========================

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-yjiuk3or/cryptography-36.0.1/setup.py", line 14, in <module>
    ap = ArgumentParser()
ModuleNotFoundError: No module named 'setuptools_rust'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/DoorPi/setup.py", line 126, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 433, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 675, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 722, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 769, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 766, in resolve
    dist = best[req.key] = env.best_match(
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1051, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1063, in obtain
    return installer(requirement)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 694, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 720, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 915, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1187, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1171, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-yjiuk3or/cryptography-36.0.1/setup.py", line 14, in <module>
    ap = ArgumentParser()
ModuleNotFoundError: No module named 'setuptools_rust'
```
  jetzt geht es nur noch zu Fuss weiter

**Comment by emphasize** [comment]
Bitte angeben:
- welche Distribution
- welches python (kann ich rauslesen)
- welche pip version `pip -V`
- welche schritte bis dahin durchgeführt wurden (die komplette abfolge)
- ist das ein frisches system?
- ...

Bitte strukturiert diese in separaten issues

_edit: Hab ein bug report template erstellt_

`pyasn1-modules` ist kein package, das ich gesondert anfordere. Ist das eine Dependenz eines anderen? [Das](https://github.com/emphasize/DoorPi/blob/4d02b23fe8f0fa28d6ff9462d7e9c3faff2a5a89/setup.cfg#L40) sind die core packages

wurde `pyasn1` installiert? (Ich gehe mal nicht davon aus bei der Fehlermeldung - `pyasn1-modules` ist ein separates; wie ich sehe wurde das erst im zweiten durchlauf getan)

bzgl. `cryptography` / setuptools_rust: [möglicher auslöser](https://github.com/pyca/cryptography/issues/5753)
(Allerdings ist es [vorhergesehen](https://github.com/emphasize/DoorPi/blob/4d02b23fe8f0fa28d6ff9462d7e9c3faff2a5a89/setup.py#L89) das pip automatisch auf latest gebracht wird, falls nicht; aber ich seh den fehler schon)
